FORMAT: X-1A

# Test API
An example API for testing taken from https://github.com/apiaryio/api-blueprint

# Group Messages
Group of all messages-related resources.

## My Message [/message]
Let's define a header that is always sent or received with any request made on this resource in addition to what is specified in subsequent actions and their payloads (requests and responses).

+ Headers

        X-Resource-Level-Header: 40

### Retrieve a Message [GET]
Here we will define a header that is always sent or received with any request on this resource using the `GET` HTTP request method.

+ Headers

        X-Method-Level-Header: 41

+ Request Plain Text Message

    + Headers

            Accept: text/plain

+ Response 200 (text/plain)

    + Headers

            X-My-Message-Header: 42

    + Body

            Hello World!

+ Request JSON Message

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            X-My-Message-Header: 42

    + Body

            { "message": "Hello World!" }

### Update a Message [PUT]

+ Request Update Plain Text Message (text/plain)

        All your base are belong to us.

+ Request Update JSON Message (application/json)

        { "message": "All your base are belong to us." }

+ Response 204
